/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aqul.pbolaundry.view;

import com.aqul.pbolaundry.Credential;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class FormMain extends javax.swing.JFrame {

    private int xx, xy;
    protected final Credential creds;
    private Timer timer;
   
    /**
     * Creates new form FormMain
     * @param creds
     */
    public FormMain(Credential creds) {
        initComponents();
        this.creds = creds;
        
        ownerLabel.setVisible(creds.getIsOwner());
        mainPanelHistoryOrder.setVisible(creds.getIsOwner());
        mainPanelUser.setVisible(creds.getIsOwner());
        
        userLabel.setText(creds.getUsername());
        setTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();
        mainPanelCreateOrder = new javax.swing.JPanel();
        linePanelCreateOrder = new javax.swing.JPanel();
        iconCreateOrder = new javax.swing.JLabel();
        buttonCreateOrder = new javax.swing.JLabel();
        mainPanelStatusOrder = new javax.swing.JPanel();
        linePanelStatusOrder = new javax.swing.JPanel();
        iconStatusOrder = new javax.swing.JLabel();
        buttonStatusOrder = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        mainPanelHistoryOrder = new javax.swing.JPanel();
        linePanelHistoryOrder = new javax.swing.JPanel();
        iconHistoryOrder = new javax.swing.JLabel();
        buttonHistoryOrder = new javax.swing.JLabel();
        mainPanelUser = new javax.swing.JPanel();
        linePanelUser = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        buttonUser = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        custom_JPanelGradient1 = new com.aqul.pbolaundry.palette.Custom_JPanelGradient();
        buttonClose = new javax.swing.JLabel();
        buttonProfile = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        panelDasar = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/logo.png")).getImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setText("Laudry App");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-50.png"))); // NOI18N
        jLabel1.setLabelFor(titleLabel);

        mainLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(153, 153, 153));
        mainLabel.setText("MAIN");

        mainPanelCreateOrder.setBackground(new java.awt.Color(255, 255, 255));

        linePanelCreateOrder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linePanelCreateOrderLayout = new javax.swing.GroupLayout(linePanelCreateOrder);
        linePanelCreateOrder.setLayout(linePanelCreateOrderLayout);
        linePanelCreateOrderLayout.setHorizontalGroup(
            linePanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        linePanelCreateOrderLayout.setVerticalGroup(
            linePanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        iconCreateOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCreateOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-order-30.png"))); // NOI18N

        buttonCreateOrder.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonCreateOrder.setForeground(new java.awt.Color(102, 102, 102));
        buttonCreateOrder.setText("Create Order");
        buttonCreateOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCreateOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCreateOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCreateOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCreateOrderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelCreateOrderLayout = new javax.swing.GroupLayout(mainPanelCreateOrder);
        mainPanelCreateOrder.setLayout(mainPanelCreateOrderLayout);
        mainPanelCreateOrderLayout.setHorizontalGroup(
            mainPanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelCreateOrderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconCreateOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelCreateOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        mainPanelCreateOrderLayout.setVerticalGroup(
            mainPanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelCreateOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(mainPanelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelCreateOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mainPanelStatusOrder.setBackground(new java.awt.Color(255, 255, 255));

        linePanelStatusOrder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linePanelStatusOrderLayout = new javax.swing.GroupLayout(linePanelStatusOrder);
        linePanelStatusOrder.setLayout(linePanelStatusOrderLayout);
        linePanelStatusOrderLayout.setHorizontalGroup(
            linePanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        linePanelStatusOrderLayout.setVerticalGroup(
            linePanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        iconStatusOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconStatusOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-status-30.png"))); // NOI18N

        buttonStatusOrder.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonStatusOrder.setForeground(new java.awt.Color(102, 102, 102));
        buttonStatusOrder.setText("Status Order");
        buttonStatusOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonStatusOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStatusOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonStatusOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonStatusOrderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelStatusOrderLayout = new javax.swing.GroupLayout(mainPanelStatusOrder);
        mainPanelStatusOrder.setLayout(mainPanelStatusOrderLayout);
        mainPanelStatusOrderLayout.setHorizontalGroup(
            mainPanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelStatusOrderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconStatusOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStatusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelStatusOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelStatusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        mainPanelStatusOrderLayout.setVerticalGroup(
            mainPanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelStatusOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonStatusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconStatusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(mainPanelStatusOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelStatusOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelStatusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ownerLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ownerLabel.setForeground(new java.awt.Color(153, 153, 153));
        ownerLabel.setText("OWNER");

        mainPanelHistoryOrder.setBackground(new java.awt.Color(255, 255, 255));

        linePanelHistoryOrder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linePanelHistoryOrderLayout = new javax.swing.GroupLayout(linePanelHistoryOrder);
        linePanelHistoryOrder.setLayout(linePanelHistoryOrderLayout);
        linePanelHistoryOrderLayout.setHorizontalGroup(
            linePanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        linePanelHistoryOrderLayout.setVerticalGroup(
            linePanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        iconHistoryOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconHistoryOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-history-30.png"))); // NOI18N

        buttonHistoryOrder.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonHistoryOrder.setForeground(new java.awt.Color(102, 102, 102));
        buttonHistoryOrder.setText("History Order");
        buttonHistoryOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHistoryOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHistoryOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHistoryOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHistoryOrderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelHistoryOrderLayout = new javax.swing.GroupLayout(mainPanelHistoryOrder);
        mainPanelHistoryOrder.setLayout(mainPanelHistoryOrderLayout);
        mainPanelHistoryOrderLayout.setHorizontalGroup(
            mainPanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelHistoryOrderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconHistoryOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHistoryOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelHistoryOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelHistoryOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        mainPanelHistoryOrderLayout.setVerticalGroup(
            mainPanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelHistoryOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonHistoryOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconHistoryOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(mainPanelHistoryOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelHistoryOrderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelHistoryOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mainPanelUser.setBackground(new java.awt.Color(255, 255, 255));

        linePanelUser.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linePanelUserLayout = new javax.swing.GroupLayout(linePanelUser);
        linePanelUser.setLayout(linePanelUserLayout);
        linePanelUserLayout.setHorizontalGroup(
            linePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        linePanelUserLayout.setVerticalGroup(
            linePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        iconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N

        buttonUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonUser.setForeground(new java.awt.Color(102, 102, 102));
        buttonUser.setText("User");
        buttonUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainPanelUserLayout = new javax.swing.GroupLayout(mainPanelUser);
        mainPanelUser.setLayout(mainPanelUserLayout);
        mainPanelUserLayout.setHorizontalGroup(
            mainPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelUserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        mainPanelUserLayout.setVerticalGroup(
            mainPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(mainPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelUserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(linePanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ownerLabel))
                    .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mainPanelCreateOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(mainLabel))
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(mainPanelStatusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPanelHistoryOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanelCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainPanelStatusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ownerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanelHistoryOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        panelKanan.setLayout(new java.awt.BorderLayout());

        custom_JPanelGradient1.setColorEnd(new java.awt.Color(153, 255, 255));
        custom_JPanelGradient1.setColorStart(new java.awt.Color(0, 204, 204));

        buttonClose.setForeground(new java.awt.Color(102, 102, 102));
        buttonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonClose.setText("x");
        buttonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseMouseClicked(evt);
            }
        });

        buttonProfile.setBackground(new java.awt.Color(153, 255, 255));
        buttonProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male-user-30.png"))); // NOI18N
        buttonProfile.setBorderPainted(false);
        buttonProfile.setFocusPainted(false);
        buttonProfile.setFocusable(false);
        buttonProfile.setMaximumSize(new java.awt.Dimension(36, 36));
        buttonProfile.setMinimumSize(new java.awt.Dimension(36, 36));
        buttonProfile.setPreferredSize(new java.awt.Dimension(36, 36));
        buttonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfileActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        userLabel.setForeground(new java.awt.Color(102, 102, 102));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel.setText("User");

        dateLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(102, 102, 102));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date");

        javax.swing.GroupLayout custom_JPanelGradient1Layout = new javax.swing.GroupLayout(custom_JPanelGradient1);
        custom_JPanelGradient1.setLayout(custom_JPanelGradient1Layout);
        custom_JPanelGradient1Layout.setHorizontalGroup(
            custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelGradient1Layout.createSequentialGroup()
                .addGap(0, 401, Short.MAX_VALUE)
                .addGroup(custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelGradient1Layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        custom_JPanelGradient1Layout.setVerticalGroup(
            custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelGradient1Layout.createSequentialGroup()
                .addComponent(buttonClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        panelKanan.add(custom_JPanelGradient1, java.awt.BorderLayout.PAGE_START);

        panelDasar.setBackground(new java.awt.Color(250, 250, 250));

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));
        panelUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelDasarLayout = new javax.swing.GroupLayout(panelDasar);
        panelDasar.setLayout(panelDasarLayout);
        panelDasarLayout.setHorizontalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelDasarLayout.setVerticalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        panelKanan.add(panelDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCreateOrderMouseEntered
        mainPanelCreateOrder.setBackground(new Color(250, 250, 250));
        linePanelCreateOrder.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_buttonCreateOrderMouseEntered

    private void buttonCreateOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCreateOrderMouseExited
        mainPanelCreateOrder.setBackground(new Color(250, 255, 255));
        linePanelCreateOrder.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buttonCreateOrderMouseExited

    private void buttonCreateOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCreateOrderMouseClicked
        mainPanelCreateOrder.setBackground(new Color(240, 240, 240));
        linePanelCreateOrder.setBackground(new Color(0, 102, 153));
        
        changePanelUtama(new MenuCreateOrder(creds));
    }//GEN-LAST:event_buttonCreateOrderMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void buttonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseMouseClicked
        dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonCloseMouseClicked

    private void buttonStatusOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStatusOrderMouseClicked
        mainPanelStatusOrder.setBackground(new Color(240, 240, 240));
        linePanelStatusOrder.setBackground(new Color(0, 102, 153));
        
        changePanelUtama(new MenuStatusOrder(this));
    }//GEN-LAST:event_buttonStatusOrderMouseClicked

    private void buttonStatusOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStatusOrderMouseEntered
        mainPanelStatusOrder.setBackground(new Color(250, 250, 250));
        linePanelStatusOrder.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_buttonStatusOrderMouseEntered

    private void buttonStatusOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStatusOrderMouseExited
        mainPanelStatusOrder.setBackground(new Color(250, 255, 255));
        linePanelStatusOrder.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buttonStatusOrderMouseExited

    private void buttonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfileActionPerformed
        DialogLogout dialog = new DialogLogout(this, true, this);
        Point p = buttonProfile.getLocationOnScreen();
        int x = p.x + buttonProfile.getWidth() - dialog.getWidth();
        int y = p.y + buttonProfile.getHeight();
        dialog.setLocation(x, y);
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonProfileActionPerformed

    private void buttonHistoryOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHistoryOrderMouseClicked
        mainPanelHistoryOrder.setBackground(new Color(240, 240, 240));
        linePanelHistoryOrder.setBackground(new Color(0, 102, 153));
        
        changePanelUtama(new MenuHistoryOrder());
    }//GEN-LAST:event_buttonHistoryOrderMouseClicked

    private void buttonHistoryOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHistoryOrderMouseEntered
        mainPanelHistoryOrder.setBackground(new Color(250, 250, 250));
        linePanelHistoryOrder.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_buttonHistoryOrderMouseEntered

    private void buttonHistoryOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHistoryOrderMouseExited
        mainPanelHistoryOrder.setBackground(new Color(250, 255, 255));
        linePanelHistoryOrder.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buttonHistoryOrderMouseExited

    private void buttonUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUserMouseClicked
        mainPanelUser.setBackground(new Color(240, 240, 240));
        linePanelUser.setBackground(new Color(0, 102, 153));
        
        changePanelUtama(new MenuUser(this));
    }//GEN-LAST:event_buttonUserMouseClicked

    private void buttonUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUserMouseEntered
        mainPanelUser.setBackground(new Color(250, 250, 250));
        linePanelUser.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_buttonUserMouseEntered

    private void buttonUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUserMouseExited
        mainPanelUser.setBackground(new Color(250, 255, 255));
        linePanelUser.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buttonUserMouseExited

    public void changePanelUtama(javax.swing.JPanel panel) {
        panelUtama.removeAll();
        panelUtama.repaint();
        panelUtama.revalidate();
        
        panelUtama.add(panel);
        panelUtama.repaint();
        panelUtama.revalidate();
    }

    private void setTimer() {
        timer = new Timer(1000, (ActionEvent  e) -> {
            Calendar calender = Calendar.getInstance();
            Date now = new Date();
            SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
            SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            String hari = formatHari.format(calender.getTime());
            String waktuTangal = formatTanggal.format(now);
            dateLabel.setText(hari + ", " + waktuTangal);
        });
        
        timer.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonClose;
    private javax.swing.JLabel buttonCreateOrder;
    private javax.swing.JLabel buttonHistoryOrder;
    private javax.swing.JButton buttonProfile;
    private javax.swing.JLabel buttonStatusOrder;
    private javax.swing.JLabel buttonUser;
    private com.aqul.pbolaundry.palette.Custom_JPanelGradient custom_JPanelGradient1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel iconCreateOrder;
    private javax.swing.JLabel iconHistoryOrder;
    private javax.swing.JLabel iconStatusOrder;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel linePanelCreateOrder;
    private javax.swing.JPanel linePanelHistoryOrder;
    private javax.swing.JPanel linePanelStatusOrder;
    private javax.swing.JPanel linePanelUser;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanelCreateOrder;
    private javax.swing.JPanel mainPanelHistoryOrder;
    private javax.swing.JPanel mainPanelStatusOrder;
    private javax.swing.JPanel mainPanelUser;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
