/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aqul.pbolaundry.view;

import com.aqul.pbolaundry.Database;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class MenuAddEditUser extends javax.swing.JPanel {

    private final FormMain mainFrame;
    /**
     * Creates new form MenuAddEditUser
     * @param mainFrame
     * @param type
     * @param dataUser
     */
    public MenuAddEditUser(FormMain mainFrame, String type, String[] dataUser) {
        initComponents();
        this.mainFrame = mainFrame;
        if (type.equals("add")) {
            titleLabel.setText("Add User");
            actionButton.setText("ADD");
        } else if (type.equals("edit")) {
            titleLabel.setText("Edit User");
            actionButton.setText("EDIT");
            logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-edit-30.png")));
            userIdTextField.setText(dataUser[0]);
            nameTextField.setText(dataUser[1]);
            phoneTextField.setText(dataUser[2]);
            pointTextField.setText(dataUser[3]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userIdTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        pointTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        nameTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        phoneTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        actionButton = new javax.swing.JButton();
        nameAlert = new javax.swing.JLabel();
        phoneAlert = new javax.swing.JLabel();
        pointAlert = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setText("Add User");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-31.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("User ID");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("No. HP");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Point");

        userIdTextField.setEditable(false);
        userIdTextField.setFocusable(false);

        pointTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointTextFieldActionPerformed(evt);
            }
        });
        pointTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pointTextFieldKeyTyped(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyTyped(evt);
            }
        });

        actionButton.setBackground(new java.awt.Color(52, 152, 219));
        actionButton.setForeground(new java.awt.Color(255, 255, 255));
        actionButton.setText("ADD");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        nameAlert.setForeground(new java.awt.Color(255, 0, 0));

        phoneAlert.setForeground(new java.awt.Color(255, 0, 0));

        pointAlert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pointTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(userIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameAlert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(phoneAlert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(507, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pointAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAlert)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneAlert)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointAlert)
                .addGap(16, 16, 16)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        String userId = userIdTextField.getText();
        String name = nameTextField.getText();
        String phoneNumber = phoneTextField.getText();
        String point = pointTextField.getText();
        int parsePoint = 0;
        boolean lanjut = true;
        
        nameAlert.setText("");
        phoneAlert.setText("");
        pointAlert.setText("");
        
        if (name.isEmpty()) {
            nameAlert.setText("Harap isi nama user");
            lanjut = false;
        }
        
        if (phoneNumber.isEmpty()) {
            phoneAlert.setText("Harap isi Nomor hp user");
            lanjut = false;
        } else {
            String regexPhone = "^08[1-9][0-9]{7,10}$";
            Pattern pattern = Pattern.compile(regexPhone);
            Matcher matcher = pattern.matcher(phoneNumber);
            if (!matcher.matches()) {
                phoneAlert.setText("Nomor hp pelanggan tidak valid!");
                lanjut = false;
            }
        }
        
        if (point.isEmpty()) {
            pointAlert.setText("Harap isi point user");
            lanjut = false;
        } else {
            try {
                parsePoint = Integer.parseInt(point);
            } catch (NumberFormatException e) {
                pointAlert.setText("Point tidak valid!");
                lanjut = false;
            }
        }
        
        if (lanjut) {
            try {
                // User ID ga ada = insert
                if (userId.isEmpty()) {
                    String query = "INSERT INTO user (nama, phone_number, point) VALUES (?, ?, ?)";
                    PreparedStatement pstmt = Database.Connect().prepareStatement(query);
                    pstmt.setString(1, name);
                    pstmt.setString(2, phoneNumber);
                    pstmt.setInt(3, parsePoint);
                    int rowsInserted = pstmt.executeUpdate();
                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(this, "User berhasil ditambahkan", "Success", JOptionPane.INFORMATION_MESSAGE);
                        clearForm();
                    }
                // Jika user id ada = edit
                } else {
                    String query = "UPDATE user SET nama = ?, phone_number = ?, point = ? WHERE id = ?";
                    PreparedStatement pstmt = Database.Connect().prepareStatement(query);
                    pstmt.setString(1, name);
                    pstmt.setString(2, phoneNumber);
                    pstmt.setInt(3, parsePoint);
                    pstmt.setInt(4, Integer.parseInt(userId));
                    int rowsUpdated = pstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "User berhasil diubah", "Success", JOptionPane.INFORMATION_MESSAGE);
                        mainFrame.changePanelUtama(new MenuUser(mainFrame));
                    }
                }
            } catch (SQLException e) {
                // Handle error duplicate
                if (e.getSQLState().equals("23000") && e.getMessage().contains("Duplicate entry")) {
                    phoneAlert.setText("Nomor hp ini sudah terdaftar!");
                } else {
                    System.err.println("SQLException : " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_actionButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void pointTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointTextFieldActionPerformed

    private void phoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyTyped
        char key = evt.getKeyChar();

        // Jika karakter bukan angka, batalkan event
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextFieldKeyTyped

    private void pointTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pointTextFieldKeyTyped
        char key = evt.getKeyChar();

        // Jika karakter bukan angka, batalkan event
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_pointTextFieldKeyTyped

    private void clearForm() {
        userIdTextField.setText("");
        nameTextField.setText("");
        phoneTextField.setText("");
        pointTextField.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameAlert;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded nameTextField;
    private javax.swing.JLabel phoneAlert;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded phoneTextField;
    private javax.swing.JLabel pointAlert;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded pointTextField;
    private javax.swing.JLabel titleLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded userIdTextField;
    // End of variables declaration//GEN-END:variables
}
