/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aqul.pbolaundry.view;

import com.aqul.pbolaundry.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class MenuUser extends javax.swing.JPanel {

    private final FormMain mainFrame;
    /**
     * Creates new form MenuUser
     * @param mainFrame
     */
    public MenuUser(FormMain mainFrame) {
        initComponents();
        getListUser();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new com.aqul.pbolaundry.palette.Custom_JTable();
        editButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();
        addButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();
        deleteButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setText("User");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        editButton.setText("EDIT");
        editButton.setFillClick(new java.awt.Color(41, 128, 220));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addButton.setText("ADD");
        addButton.setFillClick(new java.awt.Color(102, 204, 0));
        addButton.setFillOriginal(new java.awt.Color(0, 204, 51));
        addButton.setFillOver(new java.awt.Color(0, 153, 0));
        addButton.setFocusCycleRoot(true);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(204, 51, 0));
        deleteButton.setText("DELETE");
        deleteButton.setFillClick(new java.awt.Color(255, 0, 0));
        deleteButton.setFillOriginal(new java.awt.Color(230, 0, 0));
        deleteButton.setFillOver(new java.awt.Color(204, 0, 0));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(logo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        mainFrame.changePanelUtama(new MenuAddEditUser(mainFrame, "add", new String[] {}));
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int row = userTable.getSelectedRow();
        if (row != -1) {
            String id = (String) userTable.getValueAt(row, 0);
            String name = (String) userTable.getValueAt(row, 1);
            String phoneNumber = (String) userTable.getValueAt(row, 2);
            String point = (String) userTable.getValueAt(row, 3);
            mainFrame.changePanelUtama(new MenuAddEditUser(mainFrame, "edit", new String[] { id, name, phoneNumber, point}));
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row = userTable.getSelectedRow();
        if (row != -1) {
            int response = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin ingin menghapus user ini?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                String id = (String) userTable.getValueAt(row, 0);
                try {
                    String query = "DELETE FROM user WHERE id = ?";
                    PreparedStatement prepare = Database.Connect().prepareStatement(query);
                    prepare.setString(1, id);
                    int rowEffect = prepare.executeUpdate();

                    if (rowEffect > 0) {
                        JOptionPane.showMessageDialog(this, "User berhasil dihapus", "Success", JOptionPane.INFORMATION_MESSAGE);
                        getListUser();
                    }

                } catch (SQLException e) {
                    System.err.println("SQLException : " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void getListUser() {
        String[] coloumn = {"ID", "Nama", "No. HP", "Point"};
        DefaultTableModel table = new DefaultTableModel(null, coloumn){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        try {
            String query = "SELECT * FROM user;";
            Connection conn = Database.Connect();
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery(query);
            
            while (result.next()) {
                int id = result.getInt("id");
                String nama = result.getString("nama");
                String noHp = result.getString("phone_number");
                int point = result.getInt("point");
                
                table.addRow(new String[] {id + "", nama, noHp, point + ""});
            }
        } catch (SQLException e) {
            System.err.println("SQLException : " + e.getMessage());
        }
        userTable.setModel(table);
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded addButton;
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded deleteButton;
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titleLabel;
    private com.aqul.pbolaundry.palette.Custom_JTable userTable;
    // End of variables declaration//GEN-END:variables
}
