/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aqul.pbolaundry.view;

import com.aqul.pbolaundry.Database;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

/**
 *
 * @author LENOVO
 */
public class MenuEditOrder extends javax.swing.JPanel {

    private final FormMain mainFrame;
    /**
     * Creates new form menuCreateOrder
     */

    /**
     * Creates new form menuCreateOrder
     * @param mainFrame
     * @param dataOrder
     */
    public MenuEditOrder(FormMain mainFrame, String[] dataOrder) {
        initComponents();
        this.mainFrame = mainFrame;
        orderIdTextField.setText(dataOrder[0]);
        orderDateTextField.setText(dataOrder[1]);
        customerNameTextField.setText(dataOrder[2]);
        customerPhoneTextField.setText(dataOrder[3]);
        serviceTextField.setText(dataOrder[4]);
        weigthTextField.setText(dataOrder[5]);
        priceTextField.setText(dataOrder[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        customerPhoneLabel = new javax.swing.JLabel();
        customerPhoneTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        serviceLabel = new javax.swing.JLabel();
        weigthLabel = new javax.swing.JLabel();
        weigthTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        updateOrderButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();
        orderIdLabel = new javax.swing.JLabel();
        orderIdTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        serviceTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        orderDateLabel = new javax.swing.JLabel();
        orderDateTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new com.aqul.pbolaundry.palette.Custom_JTextFieldRounded();
        statusLabel = new javax.swing.JLabel();
        doneCheckBox = new javax.swing.JCheckBox();
        notificationCheckBox = new javax.swing.JCheckBox();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-property-30.png"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setText("Edit Order");

        customerNameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        customerNameLabel.setText("Nama Pelanggan");

        customerNameTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        customerNameTextField.setEnabled(false);

        customerPhoneLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        customerPhoneLabel.setText("No. HP Pelanggan");

        customerPhoneTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        customerPhoneTextField.setEnabled(false);
        customerPhoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerPhoneTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerPhoneTextFieldKeyTyped(evt);
            }
        });

        serviceLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        serviceLabel.setText("Layanan");

        weigthLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        weigthLabel.setText("Berat (Kg)");

        weigthTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        weigthTextField.setEnabled(false);
        weigthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                weigthTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weigthTextFieldKeyTyped(evt);
            }
        });

        updateOrderButton.setText("UPDATE");
        updateOrderButton.setFillClick(new java.awt.Color(41, 128, 220));
        updateOrderButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        updateOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderButtonActionPerformed(evt);
            }
        });

        orderIdLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        orderIdLabel.setText("Order ID");

        orderIdTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        orderIdTextField.setEnabled(false);

        serviceTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        serviceTextField.setEnabled(false);
        serviceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serviceTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serviceTextFieldKeyTyped(evt);
            }
        });

        orderDateLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        orderDateLabel.setText("Order Date");

        orderDateTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        orderDateTextField.setEnabled(false);

        priceLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        priceLabel.setText("Harga");

        priceTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        priceTextField.setEnabled(false);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyTyped(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        statusLabel.setText("Status");

        doneCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        doneCheckBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        doneCheckBox.setText("Done");
        doneCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        notificationCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        notificationCheckBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        notificationCheckBox.setText("Send Notification to WhatsApp");
        notificationCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(serviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel))
                    .addComponent(orderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weigthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(weigthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(doneCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(notificationCheckBox)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(orderDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerPhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serviceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(orderIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(orderDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serviceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weigthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weigthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneCheckBox)
                    .addComponent(notificationCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void updateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderButtonActionPerformed
        if (doneCheckBox.isSelected()) {
            try {
                String query = "UPDATE orders SET status = 'Completed' WHERE order_id = ?";
                PreparedStatement preparedStatement = Database.Connect().prepareStatement(query);
                preparedStatement.setString(1, orderIdTextField.getText());
                int rowAffected = preparedStatement.executeUpdate();
                if (rowAffected > 0) {
                    if (notificationCheckBox.isSelected()) {
                        OkHttpClient client = new OkHttpClient().newBuilder().build();
                        RequestBody body = new MultipartBody.Builder().setType(MultipartBody.FORM)
                            .addFormDataPart("target", customerPhoneTextField.getText())
                            .addFormDataPart("message","Halo " + customerNameTextField.getText() + "\n\nPesanan laundry anda telah selesai.")
                            .build();
                        Request request = new Request.Builder()
                            .url("https://api.fonnte.com/send")
                            .method("POST", body)
                            .addHeader("Authorization", "SiCsffohwgvQjkeB1Se8")
                            .build();
                        Response response = client.newCall(request).execute();
                        if (!response.isSuccessful()) {
                            JOptionPane.showMessageDialog(this, "Gagal mengirim notifikasi ke Whatsapp", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    String querySelectOrder = "SELECT user_id, total_price FROM orders WHERE order_id = ?";
                    PreparedStatement preparedStatementSelect = Database.Connect().prepareStatement(querySelectOrder);
                    preparedStatementSelect.setString(1, orderIdTextField.getText());
                    ResultSet resultSet = preparedStatementSelect.executeQuery();
                    if (resultSet.next()) {
                        String queryUpdateUser = "UPDATE user SET point = point + ? WHERE user.id = ?";
                        PreparedStatement prstmt = Database.Connect().prepareStatement(queryUpdateUser);
                        prstmt.setInt(1, (int) Math.floor((int) resultSet.getInt("total_price") / 1000));
                        prstmt.setString(2, resultSet.getString("user_id"));
                        int rowUserAffected = prstmt.executeUpdate();
                        if (rowUserAffected <= 0) {
                            JOptionPane.showMessageDialog(this, "Gagal mengupdate point user", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Order berhasil diupdate", "Success", JOptionPane.INFORMATION_MESSAGE);
                    mainFrame.changePanelUtama(new MenuStatusOrder(mainFrame));
                }
            } catch (SQLException e) {
                System.err.println("SQLException : " + e.getMessage());
            } catch (IOException ex) {
                System.err.println("IOException : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_updateOrderButtonActionPerformed

    private void customerPhoneTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerPhoneTextFieldKeyPressed

    }//GEN-LAST:event_customerPhoneTextFieldKeyPressed

    private void customerPhoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerPhoneTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPhoneTextFieldKeyTyped

    private void weigthTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weigthTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_weigthTextFieldKeyTyped

    private void weigthTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weigthTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_weigthTextFieldKeyReleased

    private void serviceTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTextFieldKeyPressed

    private void serviceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTextFieldKeyTyped

    private void priceTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldKeyReleased

    private void priceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldKeyTyped

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNameLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded customerNameTextField;
    private javax.swing.JLabel customerPhoneLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded customerPhoneTextField;
    private javax.swing.JCheckBox doneCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JCheckBox notificationCheckBox;
    private javax.swing.JLabel orderDateLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded orderDateTextField;
    private javax.swing.JLabel orderIdLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded orderIdTextField;
    private javax.swing.JLabel priceLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded priceTextField;
    private javax.swing.JLabel serviceLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded serviceTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded updateOrderButton;
    private javax.swing.JLabel weigthLabel;
    private com.aqul.pbolaundry.palette.Custom_JTextFieldRounded weigthTextField;
    // End of variables declaration//GEN-END:variables
}
