/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aqul.pbolaundry.view;

import com.aqul.pbolaundry.Database;
import com.aqul.pbolaundry.Order;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class MenuStatusOrder extends javax.swing.JPanel {

    public FormMain mainFrame;
    /**
     * Creates new form MenuStatusOrder
     * @param mainFrame
     */
    public MenuStatusOrder(FormMain mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        getListOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new com.aqul.pbolaundry.palette.Custom_JTable();
        editButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();
        deleteButton = new com.aqul.pbolaundry.palette.Custom_JButtonRounded();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-status-30.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Status Order");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        editButton.setText("EDIT");
        editButton.setFillClick(new java.awt.Color(41, 128, 220));
        editButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.setFillClick(new java.awt.Color(255, 0, 0));
        deleteButton.setFillOriginal(new java.awt.Color(230, 0, 0));
        deleteButton.setFillOver(new java.awt.Color(204, 0, 0));
        deleteButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int row = orderTable.getSelectedRow();
        if (row != -1) {
            String id = (String) orderTable.getValueAt(row, 0);
            String tanggal = (String) orderTable.getValueAt(row, 1);
            String nama = (String) orderTable.getValueAt(row, 2);
            String nomor = (String) orderTable.getValueAt(row, 3);
            String layanan = (String) orderTable.getValueAt(row, 5);
            String berat = (String) orderTable.getValueAt(row, 6);
            String harga = (String) orderTable.getValueAt(row, 7);
            mainFrame.changePanelUtama(new MenuEditOrder(mainFrame, new String[] { id, tanggal, nama, nomor, layanan, berat, harga }));
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row = orderTable.getSelectedRow();
        if (row != -1) {
            int response = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin ingin menghapus order ini?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                String id = (String) orderTable.getValueAt(row, 0);
                try {
                    String query = "DELETE FROM orders WHERE order_id = ?";
                    PreparedStatement prepare = Database.Connect().prepareStatement(query);
                    prepare.setString(1, id);
                    int rowEffect = prepare.executeUpdate();

                    if (rowEffect > 0) {
                        JOptionPane.showMessageDialog(this, "Order berhasil dihapus", "Success", JOptionPane.INFORMATION_MESSAGE);
                        getListOrder();
                    }

                } catch (SQLException e) {
                    System.err.println("SQLException : " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void getListOrder() {
        String[] coloumn = {"ID", "Tanggal", "Nama", "No. HP", "Status", "Layanan", "Berat", "Harga"};
        DefaultTableModel table = new DefaultTableModel(null, coloumn){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        try {
            String query = "SELECT * FROM orders JOIN user ON orders.user_id = user.id JOIN service ON orders.service_id = service.id WHERE status = 'Received' ORDER BY orders.order_date ASC;";
            Connection conn = Database.Connect();
            Statement state = conn.createStatement();
            ResultSet result = state.executeQuery(query);
            
            while (result.next()) {
                String id = result.getString("order_id");
                String tanggal = result.getString("order_date");
                String nama = result.getString("customer_name");
                String noHp = result.getString("phone_number");
                String status = result.getString("status");
                String layanan = result.getString("name");
                String berat = result.getString("amount");
                String harga = "Rp. " + Order.formatWithThousandSeparator(result.getInt("total_price"));
                
                table.addRow(new String[] {id, tanggal, nama, noHp, status, layanan, berat, harga});
            }
        } catch (SQLException e) {
            System.err.println("SQLException : " + e.getMessage());
        }
        orderTable.setModel(table);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded deleteButton;
    private com.aqul.pbolaundry.palette.Custom_JButtonRounded editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private com.aqul.pbolaundry.palette.Custom_JTable orderTable;
    // End of variables declaration//GEN-END:variables
}
